using StardewModdingAPI;
using StardewModdingAPI.Events;
using StardewValley;
using System;
using System.Collections.Generic;

namespace FriendshipInsight
{
    /// <summary>
        /// Mod que muestra los cambios diarios en puntos de amistad por NPC.
            /// </summary>
                internal sealed class ModEntry : Mod
                    {
                            private readonly Dictionary<string, int> initialFriendship = new();
                                    private readonly Dictionary<string, int> yesterdayDelta = new();

                                            public override void Entry(IModHelper helper)
                                                    {
                                                                helper.Events.GameLoop.DayStarted += OnDayStarted;
                                                                            helper.Events.GameLoop.DayEnding += OnDayEnding;

                                                                                        Monitor.Log(Messages.Activation, LogLevel.Info);
                                                                                                }

                                                                                                        private void OnDayStarted(object sender, DayStartedEventArgs e)
                                                                                                                {
                                                                                                                            if (!Context.IsWorldReady || Game1.player?.friendshipData == null)
                                                                                                                                            return;

                                                                                                                                                        try
                                                                                                                                                                    {
                                                                                                                                                                                    ShowPreviousDaySummary();
                                                                                                                                                                                                    initialFriendship.Clear();

                                                                                                                                                                                                                    foreach (KeyValuePair<string, Friendship> kvp in Game1.player.friendshipData.Pairs)
                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                        string npc = kvp.Key;
                                                                                                                                                                                                                                                                            Friendship friendship = kvp.Value;
                                                                                                                                                                                                                                                                                                initialFriendship[npc] = friendship.Points;
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                        catch (Exception ex)
                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                    Monitor.Log($"⚠️ Error al iniciar el día: {ex.Message}", LogLevel.Error);
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                private void OnDayEnding(object sender, DayEndingEventArgs e)
                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                    if (!Context.IsWorldReady || Game1.player?.friendshipData == null)
                                                                                                                                                                                                                                                                                                                                                                                                                                    return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                try
                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            yesterdayDelta.Clear();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            foreach (KeyValuePair<string, Friendship> kvp in Game1.player.friendshipData.Pairs)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                string npc = kvp.Key;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Friendship friendship = kvp.Value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        int before = initialFriendship.TryGetValue(npc, out int pts) ? pts : 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int now = friendship.Points;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int delta = now - before;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (delta != 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            yesterdayDelta[npc] = delta;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    catch (Exception ex)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Monitor.Log($"⚠️ Error al finalizar el día: {ex.Message}", LogLevel.Error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            private void ShowPreviousDaySummary()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (yesterdayDelta.Count == 0)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Monitor.Log(Messages.NoChanges, LogLevel.Debug);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Monitor.Log(Messages.SummaryHeader, LogLevel.Info);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                foreach (KeyValuePair<string, int> kvp in yesterdayDelta)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            string npc = kvp.Key;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int delta = kvp.Value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Monitor.Log(FormatDeltaMessage(npc, delta), LogLevel.Info);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        private static string FormatDeltaMessage(string npc, int delta)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            string emoji = delta > 0 ? "❤️" : "💔";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        string sign = delta > 0 ? "+" : "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    string note = delta < 0 ? " ¡Ouch!" : "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return $"- {sign}{delta} {emoji} con {npc}{note}";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                /// <summary>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /// Centraliza todos los textos visibles para mantenimiento y traducción.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        /// </summary>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            internal static class Messages
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public const string Activation = "📘 Friendship Insight activado. ¡Listo para analizar corazones!";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                public const string NoChanges = "📊 Ayer no hubo cambios emocionales. Todo tranquilo en Pueblo Pelícano 🌙";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public const string SummaryHeader = "📊 Ayer ganaste:";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }